version: '3'

services:
  waterloo-carpool-demo:
    build: .
    links:
      - docker-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=passw0rd!
      - DATABASE_NAME=waterloocarpool
      - DATABASE_PORT=3306
      - DATABASE_URL=jdbc:mysql://localhost:3306/WaterlooCarpool
  docker-mysql:
      image: mysql:latest
      environment:
        - MYSQL_ROOT_PASSWORD=passw0rd!
        - MYSQL_DATABASE=waterloocarpool
        - MYSQL_PASSWORD=passw0rd!
